name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone repo to Github Action environment
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup Java Env
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
         java-version: '17'
         distribution: 'corretto'

    # Check if Java is properly installed
    - name: display java version
      run: java --version

    # Build this project
    - name: Build with Maven
      run: mvn --batch-mode -DskipTests  package 

    # Run code test
    - name: Run Tests
      run: mvn test

    # Run this fibonacci program, find Fib(10)
    - name: Run JAR
      run: java -jar target/*.jar 10
